/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package fr.memebattle.ressources.api;

import fr.memebattle.ressources.modele.api.ReponseClassement;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-06-23T13:43:47.384578900-04:00[America/New_York]")
@Validated
@Api(value = "classement", description = "the classement API")
public interface ClassementApi {

    /**
     * GET /classement : Obtenir le classement des joueurs
     * Permet d&#39;actualiser le classement dans le jeu
     *
     * @return Classement récupéré avec succès (status code 200)
     *         or Requête invalide (status code 400)
     */
    @ApiOperation(value = "Obtenir le classement des joueurs", nickname = "classementGet", notes = "Permet d'actualiser le classement dans le jeu", response = ReponseClassement.class, tags={ "Classement", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Classement récupéré avec succès", response = ReponseClassement.class),
        @ApiResponse(code = 400, message = "Requête invalide") })
    @GetMapping(
        value = "/classement",
        produces = { "*/*" }
    )
    ResponseEntity<ReponseClassement> classementGet();

}
