/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package fr.memebattle.ressources.api;

import fr.memebattle.ressources.modele.api.CreerSalon;
import fr.memebattle.ressources.modele.api.RejoindreSalon;
import fr.memebattle.ressources.modele.api.ReponseErreur;
import fr.memebattle.ressources.modele.api.ReponseSalon;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-06-02T10:39:11.257203500-04:00[America/New_York]")
@Validated
@Api(value = "salon", description = "the salon API")
public interface SalonApi {

    /**
     * POST /salon/creer : Créer un nouveau salon
     *
     * @param creerSalon Informations du salon à créer (required)
     * @return Salon créé avec succès (status code 200)
     *         or Requête invalide (status code 400)
     */
    @ApiOperation(value = "Créer un nouveau salon", nickname = "creerSalon", notes = "", response = ReponseSalon.class, tags={ "Salon", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Salon créé avec succès", response = ReponseSalon.class),
        @ApiResponse(code = 400, message = "Requête invalide", response = ReponseErreur.class) })
    @PostMapping(
        value = "/salon/creer",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<ReponseSalon> creerSalon(@ApiParam(value = "Informations du salon à créer" ,required=true )  @Valid @RequestBody CreerSalon creerSalon);


    /**
     * POST /salon/rejoindre : Rejoindre un salon existant
     *
     * @param requeteJoueur Informations du joueur à créer (required)
     * @return Succès - Le joueur a été créé avec succès (status code 200)
     *         or Requête invalide (status code 400)
     */
    @ApiOperation(value = "Rejoindre un salon existant", nickname = "rejoindreSalon", notes = "", response = ReponseSalon.class, tags={ "Salon", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Succès - Le joueur a été créé avec succès", response = ReponseSalon.class),
        @ApiResponse(code = 400, message = "Requête invalide", response = ReponseErreur.class) })
    @PostMapping(
        value = "/salon/rejoindre",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<ReponseSalon> rejoindreSalon(@ApiParam(value = "Informations du joueur à créer" ,required=true )  @Valid @RequestBody RejoindreSalon requeteJoueur);

}
