swagger: "2.0"
info:
  version: "1.0.0"
  title: Création de joueur API
paths:
  /joueur:
    post:
      tags:
        - Joueur
      summary: Créer un nouveau joueur
      operationId: creerJoueur
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: requeteJoueur
          description: Informations du joueur à créer
          required: true
          schema:
            $ref: "#/definitions/RequeteJoueur"
      responses:
        200:
          description: Joueur créé avec succès
          schema:
            $ref: "#/definitions/Joueur"
definitions:
  RequeteJoueur:
    type: object
    properties:
      pseudo:
        type: string
      age:
        type: integer
        format: int32
  Joueur:
    type: object
    properties:
      pseudo:
        type: string
      age:
        type: integer
        format: int32
