swagger: "2.0"
info:
  version: "1.0.0"
  title: API de gestion des salons MemeBattle
  description: API pour la création et la gestion des salons MemeBattle
paths:
  /salon/creer:
    post:
      tags:
        - Salon
      summary: Créer un nouveau salon
      operationId: creerSalon
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: creerSalon
          description: Informations du salon à créer
          required: true
          schema:
            $ref: "#/definitions/CreerSalon"
      responses:
        200:
          description: Salon créé avec succès
          schema:
            $ref: "#/definitions/ReponseCodeSalon"

  /salon/rejoindre:
    post:
      tags:
        - Salon
      summary: Rejoindre un salon existant
      operationId: rejoindreSalon
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: requeteJoueur
          description: Informations du joueur à créer
          required: true
          schema:
            $ref: "#/definitions/RejoindreSalon"
      responses:
        200:
          description: Succès - Le joueur a été créé avec succès
          schema:
            $ref: "#/definitions/ReponseSalon"
        400:
          description: Requête invalide
          schema:
            $ref: "#/definitions/ReponseErreur"

  /salon/quitterSalon:
    post:
      tags:
        - Salon
      summary: Quitter salon
      operationId: quitterSalon
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: le joueur qui quitte le salon
          description: joueur qui quitte le salon
          required: true
          schema:
            $ref: "#/definitions/IdJoueur"
      responses:
        200:
          description: le joueur quitte le salon

  /salon/commencer:
    post:
      tags:
        - Salon
      summary: Commencer la partie
      operationId: commencerPartie
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: commencerPartie
          description: joueur qui lance la partie
          required: true
          schema:
            $ref: "#/definitions/IdJoueur"
      responses:
        200:
          description: La partie va commencer

  /salon/listeAttente:
    get:
      tags:
        - Salon
      summary: Recuperer liste attente
      operationId: recupererListeAttente
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: La liste de joueurs en attente
          schema:
            $ref: "#/definitions/ListeJoueurs"

definitions:
  CreerSalon:
    type: object
    properties:
      maxJoueurs:
        type: integer
        format: int32
        description: Nombre de joueurs maximum du salon
        example: 6
      gameMode:
        type: string
        description: Type de partie à jouer dans le salon
        example: classique

  RejoindreSalon:
    type: object
    properties:
      pseudo:
        type: string
        description: Pseudonyme du joueur
        example: Wabfall

  ReponseSalon:
    type: object
    properties:
      idSalon:
        type: string
        description: Identifiant du salon qui vient d'être créé
        example: 223418136f238113312d96f5
      nomSalon:
        type: string
        description: Nom court du salon qui vient d'être créé
        example: OEOTW
      maxJoueurs:
        type: integer
        format: int32
        description: Nombre de joueurs maximum du salon
        example: 6
      gameMode:
        type: string
        description: Type de partie à jouer dans le salon
        example: classique
      idJoueur:
        type: string
        description: Identifiant du joueur
        example: abc123
      pseudo:
        type: string
        description: Pseudonyme du joueur
        example: Wabfall
      numJoueur:
        type: number
        description: Numero du joueur
        example:

  ReponseCodeSalon:
    type: object
    properties:
      codeSalon:
        type: string
        description: Nom court du salon qui vient d'être créé
        example: OEOTW

  IdJoueur:
    type: string
    description: idDuJoueur
    example: 649dc0aad3f99b01e287a40a

  ListeJoueurs:
    type: array
    description: liste de joueurs en attente
    items:
      type: string
      description: nom des joueurs

  ReponseErreur:
    type: object
    properties:
      message:
        type: string
        description: Message d'erreur
