swagger: "2.0"
info:
  version: "1.0.0"
  title: API de gestion des salons MemeBattle
  description: API pour la création et la gestion des salons MemeBattle
paths:
  /salon/creer:
    post:
      tags:
        - Salon
      summary: Créer un nouveau salon
      operationId: creerSalon
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: creerSalon
          description: Informations du salon à créer
          required: true
          schema:
            $ref: "#/definitions/CreerSalon"
      responses:
        200:
          description: Salon créé avec succès
          schema:
            $ref: "#/definitions/ReponseSalon"
        400:
          description: Requête invalide
          schema:
            $ref: "#/definitions/ReponseErreur"

  /salon/rejoindre:
    post:
      tags:
        - Salon
      summary: Rejoindre un salon existant
      operationId: rejoindreSalon
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: requeteJoueur
          description: Informations du joueur à créer
          required: true
          schema:
            $ref: "#/definitions/RejoindreSalon"
      responses:
        200:
          description: Succès - Le joueur a été créé avec succès
          schema:
            $ref: "#/definitions/ReponseSalon"
        400:
          description: Requête invalide
          schema:
            $ref: "#/definitions/ReponseErreur"

definitions:
  CreerSalon:
    type: object
    properties:
      maxJoueurs:
        type: integer
        format: int32
        description: Nombre de joueurs maximum du salon
        example: 6
      gameMode:
        type: string
        description: Type de partie à jouer dans le salon
        example: classique
      pseudo:
        type: string
        description: Pseudonyme du joueur
        example: Wabfall
        
  RejoindreSalon:
    type: object
    properties:
      nomSalon:
        type: string
        description: Nom du salon à rejoindre
        example: OEOTW
      pseudo:
        type: string
        description: Pseudonyme du joueur
        example: Wabfall

  ReponseSalon:
    type: object
    properties:
      idSalon:
        type: string
        description: Identifiant du salon qui vient d'être créé
        example: 223418136f238113312d96f5
      nomSalon:
        type: string
        description: Nom court du salon qui vient d'être créé
        example: OEOTW
      idJoueur:
        type: string
        description: Identifiant du joueur
        example: abc123
      pseudo:
        type: string
        description: Pseudonyme du joueur
        example: Wabfall

  ReponseErreur:
    type: object
    properties:
      message:
        type: string
        description: Message d'erreur
